name: Publish to Docker
on:
  push:
    branches:
      - master
      - gh-actions # TODO: remove

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        godot_version: ["3.0", "3.0.1"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build for Godot ${{ matrix.godot_version }}
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        GODOT_VERSION: ${{ matrix.godot_version }}
      with:
        name: "gamedrivendesign/godot-export:${{ matrix.godot_version }}"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: GODOT_VERSION