name: Publish to DockerHub
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # Note: Make sure to adjust the godot_version down below in the build-latest job when
        # adding a new version to this array.
        godot_version: ["3.0.6", "3.1", "3.1.1", "3.1.2", "3.2", "3.2.1", "3.2.2", "3.2.3", "3.4.2", "3.4.3", "3.4.4"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build for Godot ${{ matrix.godot_version }}
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        GODOT_VERSION: ${{ matrix.godot_version }}
      with:
        name: "gamedrivendesign/godot-export:${{ matrix.godot_version }}"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: GODOT_VERSION
  build-latest:
    strategy:
      matrix:
        godot_version: ["3.4.4"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Push Godot ${{ matrix.godot_version }} as "latest"
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        GODOT_VERSION: ${{ matrix.godot_version }}
      with:
        name: "gamedrivendesign/godot-export:latest"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: GODOT_VERSION
